---
rules:
	# Eslint rules
	no-multiple-empty-lines: [warn, {max: 4}]
	no-var: error

	# Plugins' rules
	flowtype/boolean-style: off
	flowtype/define-flow-type: off
	flowtype/delimiter-dangle: off
	flowtype/generic-spacing: off
	flowtype/no-weak-types: off
	flowtype/require-parameter-type: off
	flowtype/require-return-type: off
	flowtype/require-valid-file-annotation: off
	flowtype/semi: off
	flowtype/space-after-type-colon: off
	flowtype/space-before-generic-bracket: off
	flowtype/space-before-type-colon: off
	flowtype/type-id-match: off
	flowtype/union-intersection-spacing: off
	flowtype/use-flow-type: off
	flowtype/valid-syntax: off
	jsdoc/check-param-names: warn
	jsdoc/check-tag-names: warn
	jsdoc/check-types: warn
	jsdoc/newline-after-description: warn
	jsdoc/require-description-complete-sentence: warn
	jsdoc/require-hyphen-before-param-description: warn
	jsdoc/require-param: warn
	jsdoc/require-param-description: warn
	jsdoc/require-param-type: warn
	jsdoc/require-returns-description: warn
	jsdoc/require-returns-type: warn
#	xss/no-mixed-html: error
#	xss/no-location-href-assign: error
#	security/detect-unsafe-regex: error
#	security/detect-buffer-noassert: warn
#	security/detect-child-process: warn
#	security/detect-disable-mustache-escape: warn
#	security/detect-eval-with-expression: warn
#	security/detect-no-csrf-before-method-override: warn
#	security/detect-non-literal-fs-filename: warn
#	security/detect-non-literal-regexp: warn
#	security/detect-non-literal-require: warn
#	security/detect-object-injection: warn
#	security/detect-possible-timing-attacks: warn
#	security/detect-pseudoRandomBytes: warn
#	immutable/no-let: error
#	immutable/no-mutation: error
#	immutable/no-this: error
	fp/no-arguments: error
	fp/no-class: error
	fp/no-delete: error
	fp/no-events: error
	fp/no-get-set: error
	fp/no-let: error
	fp/no-loops: error
	fp/no-mutating-assign: error
	fp/no-mutating-methods: error
	fp/no-mutation: error
	fp/no-nil: error
	fp/no-proxy: error
	fp/no-rest-parameters: error
	fp/no-this: error
	fp/no-throw: error
	fp/no-unused-expression: error
	fp/no-valueof-field: error
	node/no-missing-import: error
	mocha/no-exclusive-tests: error
	mocha/no-skipped-tests: error
	mocha/no-pending-tests: error
	mocha/handle-done-callback: error
	mocha/no-global-tests: error
	mocha/no-return-and-callback: error
	mocha/no-identical-title: error
	chai-expect/no-inner-compare: error
	chai-expect/missing-assertion: error
	chai-expect/terminating-properties: error

# To consider
# https://github.com/babel/eslint-plugin-babel
