---
name: rerebrace
version: 0.0.0
description: 'React+Redux Universal Node Express with Mongo - ES6 Webpack starter '
keywords: [react, redux, webpack, babel, mongo, mongoose, express, universal, hmr]
author: geeks@perslu.com
license: MIT
main: index.js

scripts:
  prestart: npm run build
  prestart:dev: npm run build:dev
  build: webpack --config src/config/webpack.config.prod.babel.js
  build:dev: webpack --config src/config/webpack.config.dev.babel.js
  start: node src/server-entry.js
  start:dev: node src/server-entry.js
  lint: sass-lint -v -q -c ./sass-lint.yml && eslint 'src/**/*.js'
  test: npm run test:unit && npm run test:func
  test:unit: npm run mocha -- 'src/**/*.spec.js'
  test:func: npm run mocha -- 'tests/functional/**/*.func.js'
  test:e2e: npm run nightwatch -- --env local
  test:e2e-smoke: npm run nightwatch -- --env chrome_win --tag smoke
  test:e2e-xb: npm run nightwatch -- --env safari_osx,chrome_osx,firefox_win,firefox_osx,IE10,IE11,edge
  nightwatch: nightwatch -o ./tests/e2e/tests_output -c ./tests/config/nightwatch.conf.js
  mocha: 'mocha --opts ./tests/config/mocha.opts '

pre-commit: lint
pre-push: test



# Development dependencies - everything what is required to transpile, test, lint, build and bundle an app
devDependencies:


  # Babel configuration
  babel-cli: 6.14.0 # https://github.com/babel/babel/tree/master/packages/babel-cli - OBSOLETE?
  babel-core: 6.14.0 # https://github.com/babel/babel/tree/master/packages/babel-core
  # Presets
  babel-preset-es2015: 6.14.0 # https://github.com/babel/babel/tree/master/packages/babel-preset-es2015
  babel-preset-react: 6.11.1 # https://github.com/babel/babel/tree/master/packages/babel-preset-react
  # Loaders
  babel-loader: 6.2.5 # https://github.com/babel/babel-loader/tags - JS Files
  # Other
  babel-eslint: 6.1.2 # https://github.com/babel/babel-eslint/tags
  # Plugins
  babel-plugin-istanbul: 2.0.2 # https://github.com/istanbuljs/babel-plugin-istanbul/tags
  # production only
  babel-plugin-transform-react-constant-elements: 6.9.1 # https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-constant-elements
  babel-plugin-transform-react-inline-elements: 6.8.0 # https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-inline-elements
  babel-plugin-transform-react-remove-prop-types: 0.2.9 # https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types/tags


  # Webpack configuration
  webpack: 2.1.0-beta.22 # https://github.com/webpack/webpack/releases
  webpack-dev-middleware: 1.7.0 # https://github.com/webpack/webpack-dev-middleware/tags
  webpack-hot-middleware: 2.12.2 # https://github.com/glenjamin/webpack-hot-middleware/tags
  # HMR
  react-hot-loader: 3.0.0-beta.3 # https://github.com/gaearon/react-hot-loader/tags
  express-hot-reload: 0.0.1 # https://github.com/darul75/express-hot-reload/blob/master/package.json
  # plugins
  html-webpack-plugin: 2.23.0 # https://github.com/ampedandwired/html-webpack-plugin/tags
  # loaders
  image-webpack-loader: 2.0.0 # https://github.com/tcoopman/image-webpack-loader/releases
  postcss-loader: 0.13.0 # https://github.com/postcss/postcss-loader/tags
  css-loader: 0.25.0 # https://github.com/webpack/css-loader/tags

  # PostCSS
  postcss-modules: 0.5.2 # https://github.com/css-modules/postcss-modules/tags
  postcss-cssnext: 2.8.0 # https://github.com/MoOx/postcss-cssnext/tags
  postcss-focus: 1.0.0 # https://github.com/postcss/postcss-focus/tags
  postcss-reporter: 1.4.1 # https://github.com/postcss/postcss-reporter/tags
  postcss-stats-reporter: 0.1.0 # https://github.com/jeffjewiss/postcss-stats-reporter/tags
  postcss-sorting: 1.6.1 # https://github.com/hudochenkov/postcss-sorting/tags
  postcss-utilities: 0.3.0 # https://github.com/ismamz/postcss-utilities/tags
  doiuse: 2.4.1 # https://github.com/anandthakker/doiuse/tags
  sugarss: 0.1.6 # https://github.com/postcss/sugarss/tags
  precss: 1.3.0 # https://github.com/jonathantneal/precss/tags
  # Container queries - css based on parent eg. width https://github.com/ausi/cq-prolyfill
  # Removing hover for mobile devices - https://github.com/RoundingWellOS/postcss-hover/tags


  # Linting & style guides
  eslint: 3.5.0 # https://github.com/eslint/eslint/tags
  eslint-plugin-react: 6.2.0 # https://github.com/yannickcr/eslint-plugin-react/tags
  eslint-plugin-flowtype: 2.16.1 # https://github.com/gajus/eslint-plugin-flowtype
  eslint-plugin-jsdoc: 2.2.2 # https://github.com/gajus/eslint-plugin-jsdoc/tags
  eslint-plugin-xss: 0.1.8 # https://github.com/Rantanen/eslint-plugin-xss/blob/master/package.json
  eslint-plugin-security: 1.2.0 # https://github.com/nodesecurity/eslint-plugin-security/tags
  eslint-plugin-new-with-error: 1.1.0 # https://github.com/Trott/eslint-plugin-new-with-error/blob/master/package.json
  eslint-plugin-immutable: 1.0.0 # https://github.com/jhusain/eslint-plugin-immutable/blob/master/package.json
  eslint-plugin-fp: 2.2.0 # https://github.com/jfmengels/eslint-plugin-fp/tags
  eslint-plugin-node: 2.0.0 # https://github.com/mysticatea/eslint-plugin-node/tags
  eslint-plugin-mocha: 4.5.1 # https://github.com/lo1tuma/eslint-plugin-mocha/tags
  eslint-plugin-chai-expect: 1.1.1 # https://github.com/Turbo87/eslint-plugin-chai-expect/tags
  eslint-plugin-jsx-a11: 2.2.1 # https://github.com/evcohen/eslint-plugin-jsx-a11y/tags
  eslint-plugin-import: 1.14.0 # https://github.com/benmosher/eslint-plugin-import/tags - required by airbnb config
  eslint-import-resolver-webpack: 0.5.1 # https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/webpack/package.json
  eslint-import-resolver-node: 0.2.3 # https://github.com/benmosher/eslint-plugin-import/blob/master/resolvers/node/package.json
  eslint-config-airbnb: 11.0.0
  stylelint: 7.2.0 # https://github.com/stylelint/stylelint/tags
  stylelint-config-standard: 13.0.0 # https://github.com/stylelint/stylelint-config-standard/tags

  # Testing
  karma: 1.3.0 # https://github.com/karma-runner/karma/tags
  karma-phantomjs-launcher: 1.0.2 # https://github.com/karma-runner/karma-phantomjs-launcher/tags
  karma-chrome-launcher: 2.0.0 # https://github.com/karma-runner/karma-chrome-launcher/tags
  karma-safari-launcher: 1.0.0 # https://github.com/karma-runner/karma-safari-launcher/tags
  karma-firefox-launcher: 1.0.0 # https://github.com/karma-runner/karma-firefox-launcher/tags
  karma-ie-launcher: 1.0.0 # https://github.com/karma-runner/karma-ie-launcher/tags
  karma-mocha: 1.1.1 # https://github.com/karma-runner/karma-mocha/tags
  karma-mocha-reporter: 2.1.0 # https://github.com/litixsoft/karma-mocha-reporter/tags
  karma-sourcemap-loader: 0.3.7 # https://github.com/demerzel3/karma-sourcemap-loader/blob/master/package.json
  karma-webpack: 1.8.0 # https://github.com/webpack/karma-webpack/tags
  karma-coverage: 1.1.1 # https://github.com/karma-runner/karma-coverage/tags
  karma-intellij: 1.0.0 # https://github.com/karma-runner/karma-intellij/blob/master/package.json
  istanbul: 0.4.5 # https://github.com/gotwarlost/istanbul/tags
  nyc: 8.2.0 # https://github.com/istanbuljs/nyc/tags - Istanbul CLI
  nightwatch: 0.9.8 # https://github.com/nightwatchjs/nightwatch/tags
  sinon: 2.0.0-pre.2 # https://github.com/sinonjs/sinon/tags
  expect: 1.20.2 # https://github.com/mjackson/expect/tags
  expect-jsx: 2.6.0 # https://github.com/algolia/expect-jsx/tags
  expect-immutable: 0.0.3 # https://github.com/hunterc/expect-immutable/tags
  enzyme: 2.4.1 # https://github.com/airbnb/enzyme/tags
  chai: 3.5.0 # https://github.com/chaijs/chai/tags
  chai-enzyme: 0.5.1 # https://github.com/producthunt/chai-enzyme/tags
  chai-immutable: 1.6.0 # https://github.com/astorije/chai-immutable/tags
  jsx-chai: 4.0.0 # https://github.com/bkonkle/jsx-chai/tags

  # System tools
  rimraf: 2.5.4 # https://github.com/isaacs/rimraf/tags
  cross-env: 2.0.1 # https://github.com/kentcdodds/cross-env/tags

  # Code generating
  plop: 1.5.0 # https://github.com/amwmedia/plop/tags

  # Browser package management
  jspm: 0.16.45 # https://github.com/jspm/jspm-cli/tags


  # Found somewhere, don't know what it does




  # DROPPED
  # babel-plugin-react-transform replaced by react-hot-loader


# Engines requirements spec
engines:
  node: ">=6.5.0" # Required for native support of ES6 in server. No more ugly transpiling when it is not needed
  npm: ">=3.0.0"


# Babel configuration
babel:
  # All options are default and can be overriden by 'env' option below
  sourceMaps: both
  compact: false
  # During transpiling plugins run before presets
  #plugins: # Plugins ordering is: FIRST to LAST
    # - transform-react-jsx # Runs first

  # Preset: react
  # syntax-flow
  # syntax-jsx
  # transform-flow-strip-types
  # transform-react-jsx
  # transform-react-display-name
  presets: # Plugins ordering is: LAST to FIRST
    - [es2015, {modules: false}] # Runs last. modules - we want to work with ES6 modules. No transformation for AMD, UMD, SystemJS or CommonJS (Defaults to CommonJS)
    - react # Runs first

  #ignore:
  #  - foo.js # TODO DUMMY EXAMPLE
  #  - bar/**/*.js # TODO DUMMY EXAMPLE
  env: # Based on BABEL_ENV
    production: # BABEL_ENV=production
      sourceMaps: false
      minified: true
      comments: false
      compact: true
      plugins:
        # From React Lego starter https://github.com/peter-mouland/react-lego/blob/master/.babelrc
        - transform-react-remove-prop-types
        - transform-react-constant-elements
        - transform-react-inline-elements
    test:
      plugins:
        - istanbul


eslintConfig:
  ---
  root: true
  parser: babel-eslint
  parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
      jsx: true
  env:
    es6: true
    browser: true
    node: true
    mocha: true
    protractor: true
    # commonjs: true # used for webpack, but is it required if targetting es6 modules?
  plugins:
    - flowtype # Rules: https://github.com/gajus/eslint-plugin-flowtype
    - react # Rules: https://github.com/yannickcr/eslint-plugin-react
    - jsdoc # Rules: https://github.com/gajus/eslint-plugin-jsdoc
    - xss
    - security
    - jsx-a11y # TODO DEFINE RULES
    - immutable
    - fp
    - node
    - import
    - mocha
    - chai-expect
  extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:node/recommended
    - plugin:import/errors
    - plugin:import/warnings
    - airbnb
  settings:
    flowtype:
      onlyFilesWithFlowAnnotation: false
    import/resolver:
        webpack:
          config: 'webpack.multiple.config.js'
  rules:
    flowtype/boolean-style: [error, boolean]
    flowtype/define-flow-type: warning
    flowtype/delimiter-dangle: [error, always]
    flowtype/generic-spacing: [error, never]
    flowtype/no-weak-types: error # TODO VERIFY THIS AND BELOW
    flowtype/require-parameter-type: error
    flowtype/require-return-type: [error, always, {annotateUndefined: never}]
    flowtype/require-valid-file-annotation: error
    flowtype/semi: [error, always]
    flowtype/space-after-type-colon: [error, always]
    flowtype/space-before-generic-bracket: [error, never]
    flowtype/space-before-type-colon: [error, never]
    flowtype/type-id-match: [error, "^([A-Z][a-z0-9]+)+Type$"]
    flowtype/union-intersection-spacing: [error, always]
    flowtype/use-flow-type: warning
    flowtype/valid-syntax: warning
    jsdoc/check-param-names: warning
    jsdoc/check-tag-names: warning
    jsdoc/check-types: warning
    jsdoc/newline-after-description: warning
    jsdoc/require-description-complete-sentence: warning
    jsdoc/require-hyphen-before-param-description: warning
    jsdoc/require-param: warning
    jsdoc/require-param-description: warning
    jsdoc/require-param-type: warning
    jsdoc/require-returns-description: warning
    jsdoc/require-returns-type: warning
    xss/no-mixed-html: error
    xss/no-location-href-assign: error
    security/detect-unsafe-regex: error
    security/detect-buffer-noassert: warning
    security/detect-child-process: warning
    security/detect-disable-mustache-escape: warning
    security/detect-eval-with-expression: warning
    security/detect-no-csrf-before-method-override: warning
    security/detect-non-literal-fs-filename: warning
    security/detect-non-literal-regexp: warning
    security/detect-non-literal-require: warning
    security/detect-object-injection: warning
    security/detect-possible-timing-attacks: warning
    security/detect-pseudoRandomBytes: warning
    immutable/no-let: error
    immutable/no-mutation: error
    immutable/no-this: error
    fp/no-arguments: error
    fp/no-class: error
    fp/no-delete: error
    fp/no-events: error
    fp/no-get-set: error
    fp/no-let: error
    fp/no-loops: error
    fp/no-mutating-assign: error
    fp/no-mutating-methods: error
    fp/no-mutation: error
    fp/no-nil: error
    fp/no-proxy: error
    fp/no-rest-parameters: error
    fp/no-this: error
    fp/no-throw: error
    fp/no-unused-expression: error
    fp/no-valueof-field: error
    no-var: error
    node/no-missing-import: error
    mocha/no-exclusive-tests: error
    mocha/no-skipped-tests: error
    mocha/no-pending-tests: error
    mocha/handle-done-callback: error
    mocha/no-global-tests: error
    mocha/no-return-and-callback: error
    mocha/no-identical-title: error
    no-inner-compare: error
    missing-assertion: error
    terminating-properties: error

  # To consider
  # https://github.com/babel/eslint-plugin-babel

stylelint:
  extends: stylelint-config-standard
  rules:
    indentation: tab